// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: player_simple.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Player 玩家数据表
type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 主键
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Exp           int64                  `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	XVersion      int64                  `protobuf:"varint,5,opt,name=_version,json=Version,proto3" json:"_version,omitempty"` // 运行时字段
	Ctime         int64                  `protobuf:"varint,6,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Mtime         int64                  `protobuf:"varint,7,opt,name=mtime,proto3" json:"mtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_player_simple_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_player_simple_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_player_simple_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Player) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *Player) GetXVersion() int64 {
	if x != nil {
		return x.XVersion
	}
	return 0
}

func (x *Player) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *Player) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

// Item 道具表（复合主键示例）
type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 主键
	ItemId        int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`       // 主键
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XVersion      int64                  `protobuf:"varint,4,opt,name=_version,json=Version,proto3" json:"_version,omitempty"` // 运行时字段
	Ctime         int64                  `protobuf:"varint,5,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Mtime         int64                  `protobuf:"varint,6,opt,name=mtime,proto3" json:"mtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_player_simple_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_player_simple_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_player_simple_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Item) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *Item) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Item) GetXVersion() int64 {
	if x != nil {
		return x.XVersion
	}
	return 0
}

func (x *Item) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *Item) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

var File_player_simple_proto protoreflect.FileDescriptor

const file_player_simple_proto_rawDesc = "" +
	"\n" +
	"\x13player_simple.proto\x12\x04test\"\xa8\x01\n" +
	"\x06Player\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x04 \x01(\x03R\x03exp\x12\x19\n" +
	"\b_version\x18\x05 \x01(\x03R\aVersion\x12\x14\n" +
	"\x05ctime\x18\x06 \x01(\x03R\x05ctime\x12\x14\n" +
	"\x05mtime\x18\a \x01(\x03R\x05mtime\"\x99\x01\n" +
	"\x04Item\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\x12\x19\n" +
	"\b_version\x18\x04 \x01(\x03R\aVersion\x12\x14\n" +
	"\x05ctime\x18\x05 \x01(\x03R\x05ctime\x12\x14\n" +
	"\x05mtime\x18\x06 \x01(\x03R\x05mtimeB*Z(lucky/server/pkg/xdb/protoc-gen-xdb/testb\x06proto3"

var (
	file_player_simple_proto_rawDescOnce sync.Once
	file_player_simple_proto_rawDescData []byte
)

func file_player_simple_proto_rawDescGZIP() []byte {
	file_player_simple_proto_rawDescOnce.Do(func() {
		file_player_simple_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_player_simple_proto_rawDesc), len(file_player_simple_proto_rawDesc)))
	})
	return file_player_simple_proto_rawDescData
}

var file_player_simple_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_player_simple_proto_goTypes = []any{
	(*Player)(nil), // 0: test.Player
	(*Item)(nil),   // 1: test.Item
}
var file_player_simple_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_player_simple_proto_init() }
func file_player_simple_proto_init() {
	if File_player_simple_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_player_simple_proto_rawDesc), len(file_player_simple_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_player_simple_proto_goTypes,
		DependencyIndexes: file_player_simple_proto_depIdxs,
		MessageInfos:      file_player_simple_proto_msgTypes,
	}.Build()
	File_player_simple_proto = out.File
	file_player_simple_proto_goTypes = nil
	file_player_simple_proto_depIdxs = nil
}
