package main

import (
	"bytes"
	"text/template"
)

// TemplateData 模板数据结构
type TemplateData struct {
	// 基本信息
	PackageName string
	Version     string
	MessageName string

	// 字段信息
	Fields      []FieldInfo
	PKFields    []FieldInfo
	FieldPrefix string // 字段常量前缀，如 "PlayerField"

	// 类型信息
	RecordName     string // 如 "PlayerRecord"
	PKName         string // 如 "PlayerPK"
	CommitmentName string // 如 "PlayerCommitment"
	SourceName     string // 如 "_PlayerSource"

	// Source 配置
	TableName  string
	DriverName string
	Namespace  string
	KeySize    int

	// 导入包
	Imports []ImportInfo
}

// FieldInfo 字段信息
type FieldInfo struct {
	GoName    string // Go 字段名
	ProtoName string // Proto 字段名
	GoType    string // Go 类型
	IsPK      bool   // 是否为主键
	IsRuntime bool   // 是否为运行时字段
	ConstName string // 常量名，如 "PlayerFieldPlayerId"
	Comment   string // 字段注释
}

// ImportInfo 导入包信息
type ImportInfo struct {
	Path  string
	Alias string // 别名，如 "proto"
}

// 模板定义
var (
	// fileHeaderTemplate 文件头模板
	fileHeaderTemplate = `// Code generated by protoc-gen-xdb. DO NOT EDIT.
// versions:
//	protoc-gen-xdb {{.Version}}

package {{.PackageName}}

import (
{{- range .Imports}}
	{{- if .Alias}}
	{{.Alias}} "{{.Path}}"
	{{- else}}
	"{{.Path}}"
	{{- end}}
{{- end}}
)
`

	// fieldConstantsTemplate 字段常量模板
	fieldConstantsTemplate = `
// Field constants for {{.MessageName}}
const (
{{- range $index, $field := .Fields}}
	{{- if $index | eq 0}}
	{{$field.ConstName}} xdb.Field = iota
	{{- else}}
	{{$field.ConstName}}
	{{- end}}
{{- end}}
)
`

	// pkTemplate PK 结构体模板
	pkTemplate = `
// {{.PKName}} 主键
type {{.PKName}} struct {
{{- range .PKFields}}
	{{.GoName}} {{.GoType}}
{{- end}}
{{- if gt (len .PKFields) 1}}
	validFieldNum int
{{- end}}
}

func (pk *{{.PKName}}) Source() *xdb.Source {
	return {{.SourceName}}
}

func (pk *{{.PKName}}) String() string {
	{{- if eq (len .PKFields) 1}}
	return fmt.Sprintf("{{.Namespace}}:%v", pk.{{(index .PKFields 0).GoName}})
	{{- else}}
	return fmt.Sprintf("{{.Namespace}}:%v{{range $i := (seq (sub (len $.PKFields) 1))}}:%v{{end}}",
		{{- range $i, $field := .PKFields}}
		{{- if $i | eq 0}}
		pk.{{$field.GoName}},
		{{- else}}
		pk.{{$field.GoName}},
		{{- end}}
		{{- end}}
	)
	{{- end}}
}

func (pk *{{.PKName}}) HashGroup() int {
	{{- if gt (len .PKFields) 0}}
	return int(pk.{{(index .PKFields 0).GoName}} % 16)
	{{- else}}
	return 0
	{{- end}}
}

func (pk *{{.PKName}}) Empty() bool {
	{{- if eq (len .PKFields) 1}}
	return pk.{{(index .PKFields 0).GoName}} == 0
	{{- else}}
	return pk.validFieldNum == 0
	{{- end}}
}

func (pk *{{.PKName}}) PrefixOf(key xdb.Key) bool {
	_, ok := key.(*{{.PKName}})
	if !ok {
		return false
	}
	// TODO: 实现前缀匹配逻辑
	return false
}

func (pk *{{.PKName}}) Full() bool {
	{{- if eq (len .PKFields) 1}}
	return pk.{{(index .PKFields 0).GoName}} != 0
	{{- else}}
	return pk.validFieldNum == {{len .PKFields}}
	{{- end}}
}

func (pk *{{.PKName}}) FetchFilter() interface{} {
	filter := make(map[string]interface{})
	{{- range .PKFields}}
	if pk.{{.GoName}} != 0 {
		filter["{{.ProtoName}}"] = pk.{{.GoName}}
	}
	{{- end}}
	return filter
}
`

	// recordTemplate Record 结构体模板
	recordTemplate = `
// {{.RecordName}} 记录结构体
type {{.RecordName}} struct {
	xdb.Header
	{{.MessageName}}
}

func (r *{{.RecordName}}) Source() *xdb.Source {
	return {{.SourceName}}
}

func (r *{{.RecordName}}) XId() string {
	{{- if eq (len .PKFields) 1}}
	return fmt.Sprintf("{{.Namespace}}:%v", r.{{(index .PKFields 0).GoName}})
	{{- else}}
	return fmt.Sprintf("{{.Namespace}}:%v{{range $i := (seq (sub (len $.PKFields) 1))}}:%v{{end}}",
		{{- range $i, $field := .PKFields}}
		{{- if eq $i 0}}
		r.{{$field.GoName}},
		{{- else}}
		r.{{$field.GoName}},
		{{- end}}
		{{- end}}
	)
	{{- end}}
}

func (r *{{.RecordName}}) Lifecycle() xdb.Lifecycle {
	return r.Header.Lifecycle()
}

func (r *{{.RecordName}}) Snapshoot() interface{} {
	return &r.{{.MessageName}}
}

func (r *{{.RecordName}}) XVersion() int64 {
	{{- $versionField := findVersionField .Fields}}
	{{- if $versionField}}
	return r.{{.MessageName}}.{{$versionField.GoName}}
	{{- else}}
	return 0
	{{- end}}
}

func (r *{{.RecordName}}) GetHeader() *xdb.Header {
	return &r.Header
}

func (r *{{.RecordName}}) MarshalJSON() ([]byte, error) {
	return json.Marshal(&r.{{.MessageName}})
}

func (r *{{.RecordName}}) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &r.{{.MessageName}})
}

func (r *{{.RecordName}}) String() string {
	{{- if gt (len .PKFields) 0}}
	return fmt.Sprintf("{{.RecordName}}{%s:%v}", "{{(index .PKFields 0).ProtoName}}", r.{{(index .PKFields 0).GoName}})
	{{- else}}
	return "{{.RecordName}}{}"
	{{- end}}
}
`

	// mutableRecordTemplate MutableRecord 方法模板
	mutableRecordTemplate = `
func (r *{{.RecordName}}) Init(ctx context.Context, data interface{}) error {
	proto, ok := data.(*{{.MessageName}})
	if !ok {
		return fmt.Errorf("invalid data type")
	}
	r.{{.MessageName}} = *proto
	r.Header.Init(xdb.LifecycleNew)
	return nil
}

func (r *{{.RecordName}}) Update(ctx context.Context, changes interface{}, fs xdb.FieldSet) error {
	proto, ok := changes.(*{{.MessageName}})
	if !ok {
		return fmt.Errorf("invalid changes type")
	}

	{{- range .Fields}}
	{{- if not .IsRuntime}}
	if fs.Contains({{.ConstName}}) {
		r.{{.GoName}} = proto.{{.GoName}}
	}
	{{- end}}
	{{- end}}
	return nil
}

func (r *{{.RecordName}}) Delete(ctx context.Context) bool {
	return r.Header.MarkAsDeleted(ctx)
}

func (r *{{.RecordName}}) Commit(ctx context.Context) (xdb.Commitment, xdb.FieldSet) {
	commitment := &{{.CommitmentName}}{
		data:      &r.{{.MessageName}},
		changes:   r.Header.Changes(),
		lifecycle: r.Header.Lifecycle(),
	}
	return commitment, r.Header.Changes()
}

func (r *{{.RecordName}}) Committing() bool {
	return r.Header.Committing()
}

func (r *{{.RecordName}}) Dirty() bool {
	return r.Header.Dirty()
}

func (r *{{.RecordName}}) SavingIndex() int32 {
	return r.Header.SavingIndex
}

func (r *{{.RecordName}}) SetSavingIndex(idx int32) {
	r.Header.SavingIndex = idx
}
`

	// sourceTemplate Source 模板
	sourceTemplate = `
var {{.SourceName}} = &xdb.Source{
	ProtoType:  reflect.TypeOf((*{{.MessageName}})(nil)).Elem(),
	RecordType: reflect.TypeOf((*{{.RecordName}})(nil)).Elem(),
	PKType:     reflect.TypeOf((*{{.PKName}})(nil)).Elem(),
	Namespace:  "{{.Namespace}}",
	DriverName: "{{.DriverName}}",
	TableName:  "{{.TableName}}",
	KeySize:    {{.KeySize}},

	PKCreator: func(args []interface{}) (xdb.PK, error) {
		if len(args) < {{.KeySize}} {
			return nil, fmt.Errorf("invalid args count")
		}
		return &{{.PKName}}{
			{{- range $i, $field := .PKFields}}
			{{$field.GoName}}: args[{{$i}}].({{$field.GoType}}),
			{{- end}}
			{{- if gt (len .PKFields) 1}}
			validFieldNum: {{len .PKFields}},
			{{- end}}
		}, nil
	},

	PKOf: func(obj interface{}) xdb.PK {
		{{- $hasModel := false}}
		{{- if $hasModel}}
		// 支持 Model 类型
		if m, ok := obj.(xdb.Model); ok {
			// 通过反射获取嵌入的 Record
			val := reflect.ValueOf(m).Elem()
			recordVal := val.FieldByName("{{.RecordName}}")
			if recordVal.IsValid() {
				record := recordVal.Interface().({{.RecordName}})
				return &{{.PKName}}{
					{{- range .PKFields}}
					{{.GoName}}: record.{{.GoName}},
					{{- end}}
					{{- if gt (len .PKFields) 1}}
					validFieldNum: {{len .PKFields}},
					{{- end}}
				}
			}
		}
		{{- end}}
		// 支持 Record 类型
		if r, ok := obj.(*{{.RecordName}}); ok {
			return &{{.PKName}}{
				{{- range .PKFields}}
				{{.GoName}}: r.{{.GoName}},
				{{- end}}
				{{- if gt (len .PKFields) 1}}
				validFieldNum: {{len .PKFields}},
				{{- end}}
			}
		}
		// 支持 proto 类型
		if p, ok := obj.(*{{.MessageName}}); ok {
			return &{{.PKName}}{
				{{- range .PKFields}}
				{{.GoName}}: p.{{.GoName}},
				{{- end}}
				{{- if gt (len .PKFields) 1}}
				validFieldNum: {{len .PKFields}},
				{{- end}}
			}
		}
		// 支持 Commitment 类型
		if c, ok := obj.(*{{.CommitmentName}}); ok {
			return &{{.PKName}}{
				{{- range .PKFields}}
				{{.GoName}}: c.data.{{.GoName}},
				{{- end}}
				{{- if gt (len .PKFields) 1}}
				validFieldNum: {{len .PKFields}},
				{{- end}}
			}
		}
		return nil
	},

	PKComparator: func(a, b interface{}) int {
		pk1 := a.(*{{.PKName}})
		pk2 := b.(*{{.PKName}})
		{{- range $i, $field := .PKFields}}
		{{- if eq $i 0}}
		if pk1.{{$field.GoName}} < pk2.{{$field.GoName}} {
			return -1
		} else if pk1.{{$field.GoName}} > pk2.{{$field.GoName}} {
			return 1
		{{- else}}
		} else if pk1.{{$field.GoName}} < pk2.{{$field.GoName}} {
			return -1
		} else if pk1.{{$field.GoName}} > pk2.{{$field.GoName}} {
			return 1
		{{- end}}
		{{- end}}
		}
		return 0
	},

	CreateCommitment: func() xdb.Commitment {
		return &{{.CommitmentName}}{}
	},
}
`

	// commitmentTemplate Commitment 模板
	commitmentTemplate = `
// {{.CommitmentName}} 提交对象
type {{.CommitmentName}} struct {
	data      *{{.MessageName}}
	changes   xdb.FieldSet
	lifecycle xdb.Lifecycle
}

func (c *{{.CommitmentName}}) Source() *xdb.Source {
	return {{.SourceName}}
}

func (c *{{.CommitmentName}}) Merge(other xdb.Commitment) bool {
	otherC, ok := other.(*{{.CommitmentName}})
	if !ok {
		return false
	}
	c.changes = c.changes.Union(otherC.changes)
	return true
}

func (c *{{.CommitmentName}}) Changes() xdb.FieldSet {
	return c.changes
}

func (c *{{.CommitmentName}}) PrepareWrite() (interface{}, interface{}) {
	return c.data, nil
}

func (c *{{.CommitmentName}}) Lifecycle() xdb.Lifecycle {
	return c.lifecycle
}

func (c *{{.CommitmentName}}) Marshal() ([]byte, error) {
	return proto.Marshal(c.data)
}

func (c *{{.CommitmentName}}) Unmarshal(data []byte) error {
	c.data = &{{.MessageName}}{}
	return proto.Unmarshal(data, c.data)
}
`

	// initTemplate 初始化模板
	initTemplate = `
func init() {
	{{.SourceName}}.PKOf = func(obj interface{}) xdb.PK {
		r := obj.(*{{.RecordName}})
		return &{{.PKName}}{
			{{- range .PKFields}}
			{{.GoName}}: r.{{.GoName}},
			{{- end}}
			{{- if gt (len .PKFields) 1}}
			validFieldNum: {{len .PKFields}},
			{{- end}}
		}
	}
	xdb.RegisterSource({{.SourceName}})
}
`
)

// executeTemplate 执行模板
func executeTemplate(tmpl *template.Template, data interface{}) (string, error) {
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// parseTemplate 解析模板字符串
func parseTemplate(name, text string) (*template.Template, error) {
	// 添加自定义函数
	funcMap := template.FuncMap{
		"seq": func(n int) []int {
			result := make([]int, n)
			for i := range result {
				result[i] = i
			}
			return result
		},
		"sub": func(a, b int) int {
			return a - b
		},
		"findVersionField": func(fields []FieldInfo) *FieldInfo {
			for i := range fields {
				if fields[i].ProtoName == "_version" || fields[i].GoName == "XVersion" {
					return &fields[i]
				}
			}
			return nil
		},
	}
	return template.New(name).Funcs(funcMap).Parse(text)
}
