#!/bin/bash

# 生成 msg 脚本
# 从 .proto 文件生成消息定义文件

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "=== 生成 msg 文件 ==="
echo ""

# 创建输出目录
MSG_DIR="$SCRIPT_DIR/gen/msg"
mkdir -p "$MSG_DIR"

# 查找所有 .proto 文件
PROTO_FILES=$(find . -maxdepth 1 -name "*.proto" -type f)

if [ -z "$PROTO_FILES" ]; then
    echo "⚠ 未找到 .proto 文件"
    exit 0
fi

# 处理每个 .proto 文件
for proto_file in $PROTO_FILES; do
    proto_name=$(basename "$proto_file" .proto)
    msg_file="$MSG_DIR/${proto_name}_msg.go"
    
    echo "处理: $proto_file -> $msg_file"
    
    # 从 .proto 文件提取消息定义
    # 这里生成一个简单的 Go 文件，包含消息的常量定义
    cat > "$msg_file" <<EOF
// Code generated by gen_msg.sh. DO NOT EDIT.
// Source: $proto_file

package msg

import (
	"lucky/server/pkg/xdb/example/gen/pb"
)

// ${proto_name^} 消息常量
const (
	// TODO: 从 proto 文件提取消息字段常量
	// 例如: ${proto_name^}FieldPlayerId = "player_id"
)
EOF
    
    echo "  ✓ 生成: $msg_file"
done

echo ""
echo "✓ msg 文件生成完成"
echo "  输出目录: $MSG_DIR"
echo ""



