-- Code generated by protoc-gen-xdb. DO NOT EDIT.
-- source: player.proto

CREATE TABLE `player` (
    `player_id` BIGINT(20) NOT NULL DEFAULT 0,
    `name` VARCHAR(255) NOT NULL DEFAULT '',
    `level` INT(11) NOT NULL DEFAULT 0,
    `exp` BIGINT(20) NOT NULL DEFAULT 0,
    `ctime` BIGINT(20) NOT NULL DEFAULT 0,
    `mtime` BIGINT(20) NOT NULL DEFAULT 0,
    PRIMARY KEY(`player_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
